FROM datamechanics/spark:3.1.3-hadoop-3.2.0-java-11-scala-2.12-python-3.8-latest
WORKDIR /opt/spark/


RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.227/aws-java-sdk-bundle-1.12.227.jar
RUN mv aws-java-sdk-bundle-1.12.227.jar /opt/spark/jars

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

COPY ./requirements.txt .
RUN pip3 install -r requirements.txt
COPY ./spark_etl_script.py .